import { FilamentType } from './types';

export interface ColorPreset {
  name: string;
  hex: string;
}

export const BAMBU_COLORS: Record<string, ColorPreset[]> = {
  'PLA': [
    { name: 'Jade White', hex: '#F5F5F5' },
    { name: 'Black', hex: '#1A1A1A' },
    { name: 'Grey', hex: '#808080' },
    { name: 'Red', hex: '#E60012' },
    { name: 'Blue', hex: '#0067B1' },
    { name: 'Green', hex: '#009640' },
    { name: 'Yellow', hex: '#FFD100' },
    { name: 'Orange', hex: '#F37021' },
    { name: 'Purple', hex: '#6D2D91' },
    { name: 'Pink', hex: '#E4007F' },
    { name: 'Cyan', hex: '#00A0E9' },
    { name: 'Magenta', hex: '#E4007F' },
    { name: 'Brown', hex: '#734338' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Gold', hex: '#D4AF37' },
    { name: 'Bronze', hex: '#CD7F32' },
    { name: 'Bambu Green', hex: '#00AE42' },
    { name: 'Mistletoe Green', hex: '#2D5A27' },
    { name: 'Lava Red', hex: '#A61022' },
    { name: 'Ice Blue', hex: '#A5D7E8' },
  ],
  'PLA Matte': [
    { name: 'Matte White', hex: '#F2F2F2' },
    { name: 'Matte Charcoal', hex: '#2B2B2B' },
    { name: 'Matte Ash Grey', hex: '#8C8C8C' },
    { name: 'Matte Marine Blue', hex: '#005B96' },
    { name: 'Matte Dark Blue', hex: '#002D5E' },
    { name: 'Matte Grass Green', hex: '#4F7942' },
    { name: 'Matte Dark Green', hex: '#004225' },
    { name: 'Matte Lemon Yellow', hex: '#FFF44F' },
    { name: 'Matte Mandarin Orange', hex: '#FF8800' },
    { name: 'Matte Scarlet Red', hex: '#FF2400' },
    { name: 'Matte Lilac Purple', hex: '#C8A2C8' },
    { name: 'Matte Desert Tan', hex: '#C19A6B' },
    { name: 'Matte Ivory White', hex: '#FFFFF0' },
    { name: 'Matte Sakura Pink', hex: '#FFB7C5' },
    { name: 'Matte Latte Brown', hex: '#9B7653' },
  ],
  'PLA Glow': [
    { name: 'Glow Green', hex: '#CCFF00' },
    { name: 'Glow Blue', hex: '#00FFFF' },
  ],
  'PETG': [
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Grey', hex: '#808080' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Green', hex: '#008000' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Translucent', hex: '#E0E0E0' },
  ],
  'PETG Basic': [
    { name: 'White', hex: '#F5F5F5' },
    { name: 'Black', hex: '#1A1A1A' },
    { name: 'Grey', hex: '#808080' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Red', hex: '#E60012' },
    { name: 'Orange', hex: '#F37021' },
    { name: 'Yellow', hex: '#FFD100' },
    { name: 'Green', hex: '#009640' },
    { name: 'Blue', hex: '#0067B1' },
    { name: 'Purple', hex: '#6D2D91' },
    { name: 'Pink', hex: '#E4007F' },
    { name: 'Brown', hex: '#734338' },
    { name: 'Transparent', hex: '#E0E0E0' },
  ],
  'PLA-CF': [
    { name: 'Black', hex: '#1A1A1A' },
    { name: 'Lava Red', hex: '#A61022' },
    { name: 'Dark Blue', hex: '#003366' },
    { name: 'Dark Green', hex: '#004d00' },
    { name: 'Burgundy', hex: '#800020' },
  ],
  'PETG-CF': [
    { name: 'Black', hex: '#1A1A1A' },
    { name: 'Dark Grey', hex: '#404040' },
  ],
  'TPU': [
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Black', hex: '#000000' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Green', hex: '#008000' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Neon Green', hex: '#39FF14' },
  ]
};
